@base_url = https://mct-project-t3-demo.now.sh
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VyTmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNTE4MjY4NzA0LCJleHAiOjE1MTg4NzM1MDQsInN1YiI6IjVhN2VmMTFmODQ4MWMwMDBhYmIxZjIxYSJ9.NAIq53RP9IOk3RwpNzsNYGtIuMHe9l5LBeprjUK8ITk

### List products
GET {{base_url}}/products


### Create products
POST {{base_url}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "brandName": "Ford3",
  "name": "Focus"
}

### Create account
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "userName": "testuser",
  "password": "12345"
}


### Sign in
POST  {{base_url}}/auth
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}